### ISSUE TITLE
Feature request - ETH0 as DHCP server

### ISSUE THREAD

**Issue by ghost** [cjimti/iotweb#1]
Is there an easy way to make the ETH0 act as an DHCP server? I'm trying to connect WLAN client to my mobile, which act as my internet connection (this works fine) and then through ETH0 to my routers WAN port. I'm no network specialist so I'm not sure of all the technical terms but I think in some direction bridging WLAN -> ETH0.

**Comment by cjimti** [comment]
@twikedk I'm not sure how this relates to this project.
